import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'fr' | 'en';

/** Select a localized value without duplicating language branching in JSX. */
export function localized(language: Language, french: string, english: string): string {
  return language === 'fr' ? french : english;
}

const LANGUAGE_KEY = 'orbis_language';

const translations = {
  fr: {
    brandSubtitle: 'Infrastructure Truth',
    language: 'Langue',
    french: 'Français',
    english: 'English',
    activeOrganization: 'Organisation active',
    organization: 'Organisation',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    changeTheme: 'Changer de thème',
    roles: { ADMIN: 'Administrateur', EDITOR: 'Éditeur', VIEWER: 'Lecteur' },
    nav: {
      dashboard: 'Tableau de bord',
      diagrams: 'Schémas',
      devices: 'Équipements',
      sourceOfTruth: 'Référentiel',
      discovery: 'Découverte',
      collectors: 'Collectors',
      alerts: 'Alertes',
      security: 'Sécurité',
      reports: 'Rapports',
      ipam: 'IPAM',
      dcim: 'DCIM',
      sites: 'Sites & périmètres',
      racks: 'Baies',
      users: 'Utilisateurs',
      administration: 'Administration',
    },
    dashboard: {
      title: 'Tableau de bord',
      connectedView: "Vue opérationnelle de l'infrastructure, connectée à votre périmètre actif.",
      view: "Vue opérationnelle de l'infrastructure.",
      customize: 'Personnaliser',
      visibleBlocks: 'Blocs visibles',
      keepOneBlock: 'Au moins un bloc doit rester affiché.',
      equipment: 'Équipements',
      sites: 'Sites',
      diagrams: 'Schémas',
      openAlerts: 'Alertes ouvertes',
      activeCollectors: 'Collectors actifs',
      activeReports: 'Rapports actifs',
      securityScore: 'Score sécurité',
      scope: 'Périmètre',
      site: 'Site',
      organizationShort: 'Org',
      total: 'total',
      critical: 'critique(s)',
      risks: 'risque(s)',
      typeDistribution: 'Répartition par type',
      allEquipment: 'équipements',
      globalStatus: 'État global',
      noEquipment: 'Aucun équipement',
      noData: 'Aucune donnée',
      securityRisks: 'Risques sécurité',
      analyze: 'Analyser',
      noOpenRisk: 'Aucun risque ouvert.',
      manage: 'Gérer',
      noCollector: 'Aucun collector configuré.',
      watch: 'Équipements à surveiller',
      viewAll: 'Tout voir',
      allOperational: 'Tout est opérationnel. Aucun équipement en alerte.',
      recentActivity: 'Activité récente',
      audit: 'Audit',
      noRecentActivity: 'Aucune activité récente.',
      loadingActivity: "Chargement de l'activité...",
      onboarding: 'Mise en service',
      onboardingDescription: 'Configurez les éléments essentiels de votre espace de travail.',
      done: 'Terminé',
      open: 'Ouvrir',
      firstScope: 'Définir le premier périmètre',
      createSite: 'Créer un site',
      installCollector: 'Installer un collector',
      addCollector: 'Ajouter un collector',
      importOrDiscover: 'Importer ou découvrir les équipements',
      launchDiscovery: 'Lancer la découverte',
      documentTopology: 'Documenter la topologie',
      createDiagram: 'Créer un schéma',
      organization: 'Organisation',
      neverSeen: 'jamais vu',
    },
    ui: {
      create: 'Créer',
      createNew: 'Nouveau',
      save: 'Enregistrer',
      cancel: 'Annuler',
      close: 'Fermer',
      delete: 'Supprimer',
      edit: 'Modifier',
      update: 'Mettre à jour',
      remove: 'Retirer',
      import: 'Importer',
      export: 'Exporter',
      refresh: 'Actualiser',
      search: 'Rechercher…',
      loading: 'Chargement…',
      noResults: 'Aucun résultat',
      noData: 'Aucune donnée',
      optional: 'Optionnel',
      name: 'Nom',
      description: 'Description',
      site: 'Site',
      status: 'Statut',
      type: 'Type',
      brand: 'Marque',
      model: 'Modèle',
      serial: 'N° de série',
      ip: 'Adresse IP',
      mac: 'MAC',
      vlan: 'VLAN',
      notes: 'Notes',
      documents: 'Documents',
      photos: 'Photos',
      info: 'Infos',
      ports: 'Ports',
      comments: 'Notes',
      device: 'Équipement',
      devices: 'Équipements',
      allTypes: 'Tous les types',
      allStatuses: 'Tous les statuts',
      format: "Format d'import",
      choose: '— Choisir —',
      select: '— Sélectionner —',
      success: 'Opération réussie',
      failure: 'Échec',
      created: 'créé',
      updated: 'modifié',
      deleted: 'supprimé',
    },
    alerts: {
      title: 'Alertes',
      acknowledged: 'Alerte acquittée',
      acknowledgeFailed: 'Acquittement impossible',
      saved: 'Configuration alertes enregistrée',
      invalidConfig: 'Configuration invalide',
      monitoringSaved: 'Politique monitoring enregistrée',
      invalidPolicy: 'Politique invalide',
      incidentUpdated: 'Incident mis à jour',
      incidentNotUpdated: 'Incident non modifié',
      maintenanceScheduled: 'Maintenance planifiée',
      maintenanceInvalid: 'Maintenance invalide',
      open: 'Ouvertes',
      critical: 'Critiques',
      warning: 'Warnings',
      info: 'Infos',
      all: 'Toutes',
      acknowledgedPlural: 'Acquittées',
      allSeverities: 'Toutes sévérités',
      noAlert: 'Aucune alerte dans cette vue',
      upcoming: 'Les prochains événements collector apparaîtront ici.',
      availability: 'Disponibilité 30j',
      averageLatency: 'Latence moyenne',
      openIncidents: 'Incidents ouverts',
      maintenance: 'Maintenances',
      activeIncidents: 'Incidents actifs',
      ack: 'Ack',
      resolve: 'Résoudre',
      noOpenIncident: 'Aucun incident ouvert.',
      slo: 'SLO, rétention et maintenance',
      newMaintenance: 'Nouvelle maintenance globale',
      availabilitySlo: 'SLO disponibilité (%)',
      retention: 'Rétention mesures (jours)',
      latencyWarning: 'Latence warning (ms)',
      latencyCritical: 'Latence critique (ms)',
      createLatencyAlerts: 'Créer des alertes de latence élevée',
      acknowledgedStatus: 'Acquittée',
      outboundChannels: 'Canaux sortants',
      notificationNote: 'Les alertes sont créées même si les notifications sont désactivées.',
      email: 'Email',
      genericWebhook: 'Webhook générique',
      triggerPolicy: 'Politique de déclenchement',
      triggerNote: 'Filtre les notifications sortantes, pas la création des alertes.',
      warningAndCritical: 'Warning et critique',
      criticalOnly: 'Critique uniquement',
      allSeverity: 'Toutes les sévérités',
      notifyInformative: 'Notifier aussi les événements informatifs',
    },
    reports: {
      title: 'Rapports',
      immediateExports: 'Exports immédiats',
      immediateDescription:
        'Téléchargements authentifiés avec le même périmètre organisation/site que le reste de l’application.',
      schedule: 'Planifier un rapport',
      scheduleDescription: 'Envoi automatique par email avec pièce jointe CSV ou PDF.',
      reportName: 'Nom du rapport',
      allSites: 'Tous les sites',
      firstSend: 'Premier envoi',
      timezone: 'Fuseau horaire',
      sendTime: 'Heure d’envoi',
      sendDay: 'Jour d’envoi',
      monthDay: 'Jour du mois',
      quarterDay: 'Jour du trimestre',
      recipients: 'Destinataires email',
      readOnly: 'Votre rôle permet de consulter les rapports, pas de modifier les planifications.',
      scheduled: 'Rapports planifiés',
      scheduledDescription:
        'Suivi opérationnel des prochains envois et des derniers rapports envoyés.',
      noScheduled: 'Aucun rapport planifié',
      noScheduledDescription:
        'Créez une planification pour envoyer automatiquement les exports aux équipes concernées.',
      created: 'Rapport planifié créé',
      updated: 'Planification mise à jour',
      deleted: 'Rapport planifié supprimé',
      emailSent: 'Email de test envoyé',
      smtpTest: 'Test généré sans SMTP',
      createFailed: 'Création impossible',
      updateFailed: 'Mise à jour impossible',
      deleteFailed: 'Suppression impossible',
      testFailed: 'Test impossible',
      downloadFailed: 'Téléchargement impossible',
    },
    auth: {
      sourceTruth: 'The Single Source of Infrastructure Truth.',
      description:
        'Centralisez l’inventaire, la découverte et l’exploitation de votre infrastructure dans un espace fiable, partagé et traçable.',
      footer: 'Gestion et visibilité de l’infrastructure',
      features: {
        source: {
          title: 'Source of truth',
          text: 'Inventaire, sites, IPAM et DCIM réunis dans un même espace',
        },
        discovery: {
          title: 'Découverte réseau',
          text: 'Collectors sécurisés, SNMP/LLDP et rapprochement avec votre inventaire',
        },
        operations: {
          title: 'Pilotage d’exploitation',
          text: 'Schémas, alertes, rapports et accès par organisation',
        },
      },
      login: 'Connexion',
      loginSubtitle: 'Reprenez le contrôle de votre infrastructure',
      email: 'Email',
      password: 'Mot de passe',
      forgotPassword: 'Mot de passe oublié ?',
      signIn: 'Se connecter',
      signingIn: 'Connexion…',
      or: 'ou',
      sso: 'Connexion SSO entreprise',
      ssoTitle: 'Connexion via SSO entreprise',
      ssoUnavailable: 'SSO non configuré sur cette instance',
      ssoAvailable: 'SSO disponible avec configuration administrateur.',
      noAccount: 'Pas encore de compte ?',
      createAccount: 'Créer un compte',
      success: 'Connexion réussie',
      welcome: 'Bienvenue sur Orbis',
      failure: 'Échec de la connexion',
      register: 'Créer un compte',
      registerSubtitle: 'Le premier compte devient administrateur',
      fullName: 'Nom complet',
      confirmPassword: 'Confirmer le mot de passe',
      passwordMinimum: '8 caractères minimum',
      creatingAccount: 'Création…',
      alreadyAccount: 'Déjà un compte ?',
      passwordMismatch: 'Les mots de passe ne correspondent pas',
      passwordTooShort: 'Le mot de passe doit contenir au moins 8 caractères',
      registrationFailure: 'Échec de l’inscription',
      accountCreated: 'Compte créé',
      forgotTitle: 'Mot de passe oublié',
      forgotSubtitle: 'Recevez un lien sécurisé pour reprendre l’accès',
      emailSent: 'Email envoyé si le compte existe',
      emailSentDescription:
        'Vérifiez votre boîte de réception. Le lien expire rapidement et ne peut être utilisé qu’une seule fois.',
      sendLink: 'Envoyer le lien',
      sending: 'Envoi…',
      backToLogin: 'Retour à la connexion',
      resetTitle: 'Nouveau mot de passe',
      resetSubtitle: 'Choisissez un mot de passe sécurisé',
      missingResetLink: 'Lien de réinitialisation manquant',
      updatePassword: 'Mettre à jour',
      updatingPassword: 'Mise à jour…',
      passwordUpdated: 'Mot de passe mis à jour',
      passwordUpdatedDescription: 'Vous pouvez maintenant vous connecter',
      resetFailure: 'Impossible de réinitialiser le mot de passe',
    },
  },
  en: {
    brandSubtitle: 'Infrastructure Truth',
    language: 'Language',
    french: 'Français',
    english: 'English',
    activeOrganization: 'Active organization',
    organization: 'Organization',
    settings: 'Settings',
    logout: 'Sign out',
    changeTheme: 'Change theme',
    roles: { ADMIN: 'Administrator', EDITOR: 'Editor', VIEWER: 'Viewer' },
    nav: {
      dashboard: 'Dashboard',
      diagrams: 'Diagrams',
      devices: 'Devices',
      sourceOfTruth: 'Source of truth',
      discovery: 'Discovery',
      collectors: 'Collectors',
      alerts: 'Alerts',
      security: 'Security',
      reports: 'Reports',
      ipam: 'IPAM',
      dcim: 'DCIM',
      sites: 'Sites & scopes',
      racks: 'Racks',
      users: 'Users',
      administration: 'Administration',
    },
    dashboard: {
      title: 'Dashboard',
      connectedView: 'Operational infrastructure view connected to your active scope.',
      view: 'Operational infrastructure view.',
      customize: 'Customize',
      visibleBlocks: 'Visible blocks',
      keepOneBlock: 'At least one block must remain visible.',
      equipment: 'Devices',
      sites: 'Sites',
      diagrams: 'Diagrams',
      openAlerts: 'Open alerts',
      activeCollectors: 'Active collectors',
      activeReports: 'Active reports',
      securityScore: 'Security score',
      scope: 'Scope',
      site: 'Site',
      organizationShort: 'Org',
      total: 'total',
      critical: 'critical',
      risks: 'risk(s)',
      typeDistribution: 'Distribution by type',
      allEquipment: 'devices',
      globalStatus: 'Global status',
      noEquipment: 'No devices',
      noData: 'No data',
      securityRisks: 'Security risks',
      analyze: 'Review',
      noOpenRisk: 'No open risks.',
      manage: 'Manage',
      noCollector: 'No collector configured.',
      watch: 'Devices to watch',
      viewAll: 'View all',
      allOperational: 'Everything is operational. No device is in an alert state.',
      recentActivity: 'Recent activity',
      audit: 'Audit',
      noRecentActivity: 'No recent activity.',
      loadingActivity: 'Loading activity...',
      onboarding: 'Getting started',
      onboardingDescription: 'Configure the essential elements of your workspace.',
      done: 'Done',
      open: 'Open',
      firstScope: 'Define your first scope',
      createSite: 'Create a site',
      installCollector: 'Install a collector',
      addCollector: 'Add a collector',
      importOrDiscover: 'Import or discover devices',
      launchDiscovery: 'Start discovery',
      documentTopology: 'Document the topology',
      createDiagram: 'Create a diagram',
      organization: 'Organization',
      neverSeen: 'never seen',
    },
    ui: {
      create: 'Create',
      createNew: 'New',
      save: 'Save',
      cancel: 'Cancel',
      close: 'Close',
      delete: 'Delete',
      edit: 'Edit',
      update: 'Update',
      remove: 'Remove',
      import: 'Import',
      export: 'Export',
      refresh: 'Refresh',
      search: 'Search…',
      loading: 'Loading…',
      noResults: 'No results',
      noData: 'No data',
      optional: 'Optional',
      name: 'Name',
      description: 'Description',
      site: 'Site',
      status: 'Status',
      type: 'Type',
      brand: 'Brand',
      model: 'Model',
      serial: 'Serial number',
      ip: 'IP address',
      mac: 'MAC',
      vlan: 'VLAN',
      notes: 'Notes',
      documents: 'Documents',
      photos: 'Photos',
      info: 'Info',
      ports: 'Ports',
      comments: 'Notes',
      device: 'Device',
      devices: 'Devices',
      allTypes: 'All types',
      allStatuses: 'All statuses',
      format: 'Import format',
      choose: '— Choose —',
      select: '— Select —',
      success: 'Operation successful',
      failure: 'Failed',
      created: 'created',
      updated: 'updated',
      deleted: 'deleted',
    },
    alerts: {
      title: 'Alerts',
      acknowledged: 'Alert acknowledged',
      acknowledgeFailed: 'Unable to acknowledge',
      saved: 'Alert configuration saved',
      invalidConfig: 'Invalid configuration',
      monitoringSaved: 'Monitoring policy saved',
      invalidPolicy: 'Invalid policy',
      incidentUpdated: 'Incident updated',
      incidentNotUpdated: 'Incident not updated',
      maintenanceScheduled: 'Maintenance scheduled',
      maintenanceInvalid: 'Invalid maintenance',
      open: 'Open',
      critical: 'Critical',
      warning: 'Warnings',
      info: 'Info',
      all: 'All',
      acknowledgedPlural: 'Acknowledged',
      allSeverities: 'All severities',
      noAlert: 'No alerts in this view',
      upcoming: 'Upcoming collector events will appear here.',
      availability: '30-day availability',
      averageLatency: 'Average latency',
      openIncidents: 'Open incidents',
      maintenance: 'Maintenance',
      activeIncidents: 'Active incidents',
      ack: 'Ack',
      resolve: 'Resolve',
      noOpenIncident: 'No open incidents.',
      slo: 'SLO, retention and maintenance',
      newMaintenance: 'New global maintenance',
      availabilitySlo: 'Availability SLO (%)',
      retention: 'Metric retention (days)',
      latencyWarning: 'Warning latency (ms)',
      latencyCritical: 'Critical latency (ms)',
      createLatencyAlerts: 'Create high-latency alerts',
      acknowledgedStatus: 'Acknowledged',
      outboundChannels: 'Outbound channels',
      notificationNote: 'Alerts are created even when notifications are disabled.',
      email: 'Email',
      genericWebhook: 'Generic webhook',
      triggerPolicy: 'Trigger policy',
      triggerNote: 'Filters outbound notifications, not alert creation.',
      warningAndCritical: 'Warning and critical',
      criticalOnly: 'Critical only',
      allSeverity: 'All severities',
      notifyInformative: 'Also notify informational events',
    },
    reports: {
      title: 'Reports',
      immediateExports: 'Immediate exports',
      immediateDescription:
        'Authenticated downloads using the same organization/site scope as the rest of the application.',
      schedule: 'Schedule a report',
      scheduleDescription: 'Automatic email delivery with a CSV or PDF attachment.',
      reportName: 'Report name',
      allSites: 'All sites',
      firstSend: 'First delivery',
      timezone: 'Time zone',
      sendTime: 'Delivery time',
      sendDay: 'Delivery day',
      monthDay: 'Day of month',
      quarterDay: 'Quarter day',
      recipients: 'Email recipients',
      readOnly: 'Your role allows viewing reports but not editing schedules.',
      scheduled: 'Scheduled reports',
      scheduledDescription: 'Operational view of upcoming deliveries and recently sent reports.',
      noScheduled: 'No scheduled reports',
      noScheduledDescription:
        'Create a schedule to automatically send exports to the relevant teams.',
      created: 'Scheduled report created',
      updated: 'Schedule updated',
      deleted: 'Scheduled report deleted',
      emailSent: 'Test email sent',
      smtpTest: 'Test generated without SMTP',
      createFailed: 'Creation failed',
      updateFailed: 'Update failed',
      deleteFailed: 'Deletion failed',
      testFailed: 'Test failed',
      downloadFailed: 'Download failed',
    },
    auth: {
      sourceTruth: 'The Single Source of Infrastructure Truth.',
      description:
        'Centralize infrastructure inventory, discovery and operations in a reliable, shared and auditable workspace.',
      footer: 'Infrastructure management and visibility',
      features: {
        source: {
          title: 'Source of truth',
          text: 'Inventory, sites, IPAM and DCIM in one workspace',
        },
        discovery: {
          title: 'Network discovery',
          text: 'Secure collectors, SNMP/LLDP and inventory reconciliation',
        },
        operations: {
          title: 'Operations control',
          text: 'Diagrams, alerts, reports and organization-based access',
        },
      },
      login: 'Sign in',
      loginSubtitle: 'Take control of your infrastructure',
      email: 'Email',
      password: 'Password',
      forgotPassword: 'Forgot your password?',
      signIn: 'Sign in',
      signingIn: 'Signing in…',
      or: 'or',
      sso: 'Sign in with enterprise SSO',
      ssoTitle: 'Sign in with enterprise SSO',
      ssoUnavailable: 'SSO is not configured for this instance',
      ssoAvailable: 'SSO is available after administrator configuration.',
      noAccount: 'Do not have an account yet?',
      createAccount: 'Create an account',
      success: 'Signed in successfully',
      welcome: 'Welcome to Orbis',
      failure: 'Sign-in failed',
      register: 'Create an account',
      registerSubtitle: 'The first account becomes an administrator',
      fullName: 'Full name',
      confirmPassword: 'Confirm password',
      passwordMinimum: '8 characters minimum',
      creatingAccount: 'Creating…',
      alreadyAccount: 'Already have an account?',
      passwordMismatch: 'Passwords do not match',
      passwordTooShort: 'Password must contain at least 8 characters',
      registrationFailure: 'Sign-up failed',
      accountCreated: 'Account created',
      forgotTitle: 'Forgot your password',
      forgotSubtitle: 'Receive a secure link to regain access',
      emailSent: 'Email sent if the account exists',
      emailSentDescription: 'Check your inbox. The link expires quickly and can only be used once.',
      sendLink: 'Send link',
      sending: 'Sending…',
      backToLogin: 'Back to sign in',
      resetTitle: 'New password',
      resetSubtitle: 'Choose a secure password',
      missingResetLink: 'Reset link is missing',
      updatePassword: 'Update password',
      updatingPassword: 'Updating…',
      passwordUpdated: 'Password updated',
      passwordUpdatedDescription: 'You can now sign in',
      resetFailure: 'Unable to reset the password',
    },
  },
} as const;

type TranslationShape = (typeof translations)[Language];

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: TranslationShape;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function initialLanguage(): Language {
  const stored = window.localStorage.getItem(LANGUAGE_KEY);
  if (stored === 'fr' || stored === 'en') return stored;
  return window.navigator.language.toLowerCase().startsWith('en') ? 'en' : 'fr';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => initialLanguage());

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    window.localStorage.setItem(LANGUAGE_KEY, next);
    document.documentElement.lang = next;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t: translations[language] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
